In [108]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [109]:
x = np.ones(8)
print(x)


[1. 1. 1. 1. 1. 1. 1. 1.]


## Q#2: Create y array with elements equal to 0.

In [110]:
y = np.zeros(8)
print(y)


[0. 0. 0. 0. 0. 0. 0. 0.]


## Q#3: Add x and y arrays.

In [111]:
z = np.add(x, y)
print(z)


[1. 1. 1. 1. 1. 1. 1. 1.]


## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [112]:
print("the dimension of x array: ", x.ndim)
print("the shape of x array: ", x.shape)
print("the size of x array: ", x.size)
print("the type of data in x array: ", x.dtype)


the dimension of x array:  1
the shape of x array:  (8,)
the size of x array:  8
the type of data in x array:  float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [113]:
w = np.array([
    [11, 12],
    [13, 14],
    [15, 16],
])

print(w)


[[11 12]
 [13 14]
 [15 16]]


## Q#6: Create z array contains the numbers from 1 to 3.

In [114]:
z = np.arange(1, 4)

print(z)


[1 2 3]


## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [115]:
newArray = np.hstack((w, z.reshape(-1, 1)))
print(newArray)


[[11 12  1]
 [13 14  2]
 [15 16  3]]


## Q#8: Print all elements of "newArray" using the loop.

In [116]:
for i in newArray.flatten():
    print(i)


11
12
1
13
14
2
15
16
3


## Q#9: Reverse the columns and rows of "newArray".

In [117]:
newArray = np.flip(newArray)
print(newArray)


[[ 3 16 15]
 [ 2 14 13]
 [ 1 12 11]]


## Q#10: Decrement all elements of "newArray" with 1.

In [118]:
newArray = newArray - 1
print(newArray)


[[ 2 15 14]
 [ 1 13 12]
 [ 0 11 10]]


## Q#11: Find smallest and biggest values in "newArray".

In [119]:
print("the smallest value is = ", newArray.min())
print("the biggest value is = ", newArray.max())


the smallest value is =  0
the biggest value is =  15


## Q#12: Print the first row of "newArray" using indexing.

In [120]:
print(newArray[0,])


[ 2 15 14]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [121]:
print(newArray[newArray == 12])


[12]


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [122]:
print(newArray[(newArray == 13) | (newArray == 0)])


[13  0]


## Q#15: Change the shape of "newArray" to (9,1).

In [123]:
newArray = newArray.reshape(9, 1)
print(newArray)


[[ 2]
 [15]
 [14]
 [ 1]
 [13]
 [12]
 [ 0]
 [11]
 [10]]


## Q#16: Change the shape of "newArray" to (3,3).

In [124]:
newArray = newArray.reshape(3, 3)
print(newArray)


[[ 2 15 14]
 [ 1 13 12]
 [ 0 11 10]]


# Well Done 🎉